// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudioCG.Web.Data;

#nullable disable

namespace StudioCG.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219172826_UpdateBudgetStudioPermission")]
    partial class UpdateBudgetStudioPermission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudioCG.Web.Models.AnnualitaFiscale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Anno")
                        .IsUnique();

                    b.ToTable("AnnualitaFiscali");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anno = 2025,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descrizione = "Anno Fiscale 2025",
                            IsActive = true,
                            IsCurrent = true
                        });
                });

            modelBuilder.Entity("StudioCG.Web.Models.AttivitaAnnuale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnualitaFiscaleId")
                        .HasColumnType("int");

                    b.Property<int>("AttivitaTipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AnnualitaFiscaleId");

                    b.HasIndex("AttivitaTipoId", "AnnualitaFiscaleId")
                        .IsUnique();

                    b.ToTable("AttivitaAnnuali");
                });

            modelBuilder.Entity("StudioCG.Web.Models.AttivitaCampo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttivitaTipoId")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaTipoId");

                    b.ToTable("AttivitaCampi");
                });

            modelBuilder.Entity("StudioCG.Web.Models.AttivitaTipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AttivitaTipi");
                });

            modelBuilder.Entity("StudioCG.Web.Models.BudgetStudio.BudgetSpesaMensile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mese")
                        .HasColumnType("int");

                    b.Property<int?>("MetodoPagamento")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Pagata")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VoceSpesaBudgetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoceSpesaBudgetId", "Anno", "Mese")
                        .IsUnique();

                    b.ToTable("BudgetSpeseMensili");
                });

            modelBuilder.Entity("StudioCG.Web.Models.BudgetStudio.VoceSpesaBudget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodiceSpesa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MetodoPagamentoDefault")
                        .HasColumnType("int");

                    b.Property<string>("NoteDefault")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CodiceSpesa")
                        .IsUnique();

                    b.ToTable("VociSpesaBudget");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CAP")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodiceAteco")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PEC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartitaIVA")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("RagioneSociale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoSoggetto")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("StudioCG.Web.Models.ClienteAttivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttivitaAnnualeId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCompletamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaAnnualeId");

                    b.HasIndex("ClienteId", "AttivitaAnnualeId")
                        .IsUnique();

                    b.ToTable("ClientiAttivita");
                });

            modelBuilder.Entity("StudioCG.Web.Models.ClienteAttivitaValore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttivitaCampoId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteAttivitaId")
                        .HasColumnType("int");

                    b.Property<string>("Valore")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttivitaCampoId");

                    b.HasIndex("ClienteAttivitaId", "AttivitaCampoId")
                        .IsUnique();

                    b.ToTable("ClientiAttivitaValori");
                });

            modelBuilder.Entity("StudioCG.Web.Models.ClienteSoggetto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CAP")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Citta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("CodiceFiscale")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Indirizzo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal?>("QuotaPercentuale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoSoggetto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ClientiSoggetti");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("DynamicPageId")
                        .HasColumnType("int");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("ShowInList")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DynamicPageId");

                    b.ToTable("DynamicFields");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DynamicFieldId")
                        .HasColumnType("int");

                    b.Property<int>("DynamicRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicFieldId");

                    b.HasIndex("DynamicRecordId", "DynamicFieldId")
                        .IsUnique();

                    b.ToTable("DynamicFieldValues");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TableName")
                        .IsUnique();

                    b.ToTable("DynamicPages");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DynamicPageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DynamicPageId");

                    b.ToTable("DynamicRecords");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.AccessoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan?>("OraFineMattino")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OraFinePomeriggio")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OraInizioMattino")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("OraInizioPomeriggio")
                        .HasColumnType("time");

                    b.Property<int>("ScadenzaFatturazioneId")
                        .HasColumnType("int");

                    b.Property<decimal>("TariffaOraria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ScadenzaFatturazioneId");

                    b.HasIndex("UtenteId");

                    b.ToTable("AccessiClienti");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.AnnoFatturazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AnniFatturazione");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.BilancioCEE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ScadenzaFatturazioneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScadenzaFatturazioneId");

                    b.HasIndex("ClienteId", "Anno")
                        .IsUnique();

                    b.ToTable("BilanciCEE");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.ContatoreDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Anno", "TipoDocumento")
                        .IsUnique();

                    b.ToTable("ContatoriDocumenti");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.FatturaCloud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ScadenzaFatturazioneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScadenzaFatturazioneId");

                    b.HasIndex("ClienteId", "Anno")
                        .IsUnique();

                    b.ToTable("FattureCloud");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.IncassoFattura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataIncasso")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportoIncassato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ScadenzaFatturazioneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ScadenzaFatturazioneId");

                    b.ToTable("IncassiFatture");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.IncassoProfessionista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IncassoFatturaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Percentuale")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncassoFatturaId");

                    b.HasIndex("UtenteId");

                    b.ToTable("IncassiProfessionisti");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.MandatoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportoAnnuo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("RimborsoSpese")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoScadenza")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId", "Anno")
                        .IsUnique();

                    b.ToTable("MandatiClienti");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.ScadenzaFatturazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anno")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFattura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataProforma")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportoMandato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MandatoClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NumeroFattura")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroProforma")
                        .HasColumnType("int");

                    b.Property<decimal>("RimborsoSpese")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("StatoIncasso")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MandatoClienteId");

                    b.ToTable("ScadenzeFatturazione");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.SpesaPratica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ScadenzaFatturazioneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ScadenzaFatturazioneId");

                    b.HasIndex("UtenteId");

                    b.ToTable("SpesePratiche");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("ShowInMenu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PageUrl")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pagina principale",
                            DisplayOrder = 1,
                            Icon = "fas fa-home",
                            PageName = "Dashboard",
                            PageUrl = "/Home",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gestione utenti del sistema",
                            DisplayOrder = 2,
                            Icon = "fas fa-users",
                            PageName = "Gestione Utenti",
                            PageUrl = "/Users",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 100,
                            Category = "ANAGRAFICA",
                            Description = "Gestione anagrafica clienti",
                            DisplayOrder = 10,
                            Icon = "fas fa-building",
                            PageName = "Clienti",
                            PageUrl = "/Clienti",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 101,
                            Category = "ANAGRAFICA",
                            Description = "Gestione annualità fiscali",
                            DisplayOrder = 11,
                            Icon = "fas fa-calendar-alt",
                            PageName = "Annualità Fiscali",
                            PageUrl = "/Annualita",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 102,
                            Category = "ANAGRAFICA",
                            Description = "Gestione tipi attività",
                            DisplayOrder = 12,
                            Icon = "fas fa-cogs",
                            PageName = "Tipi Attività",
                            PageUrl = "/AttivitaTipi",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 200,
                            Category = "AMMINISTRAZIONE",
                            Description = "Dashboard riepilogo fatturazione",
                            DisplayOrder = 20,
                            Icon = "fas fa-chart-line",
                            PageName = "Dashboard Fatturazione",
                            PageUrl = "/Amministrazione",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 201,
                            Category = "AMMINISTRAZIONE",
                            Description = "Gestione mandati professionali",
                            DisplayOrder = 21,
                            Icon = "fas fa-file-contract",
                            PageName = "Mandati Clienti",
                            PageUrl = "/Amministrazione/Mandati",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 202,
                            Category = "AMMINISTRAZIONE",
                            Description = "Gestione scadenze e fatturazione",
                            DisplayOrder = 22,
                            Icon = "fas fa-file-invoice-dollar",
                            PageName = "Scadenze Fatturazione",
                            PageUrl = "/Amministrazione/Scadenze",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 203,
                            Category = "AMMINISTRAZIONE",
                            Description = "Gestione spese pratiche mensili",
                            DisplayOrder = 23,
                            Icon = "fas fa-receipt",
                            PageName = "Spese Pratiche",
                            PageUrl = "/Amministrazione/SpesePratiche",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 204,
                            Category = "AMMINISTRAZIONE",
                            Description = "Registrazione accessi clienti",
                            DisplayOrder = 24,
                            Icon = "fas fa-door-open",
                            PageName = "Accessi Clienti",
                            PageUrl = "/Amministrazione/AccessiClienti",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 205,
                            Category = "AMMINISTRAZIONE",
                            Description = "Gestione Fatture in Cloud",
                            DisplayOrder = 25,
                            Icon = "fas fa-cloud",
                            PageName = "Fatture in Cloud",
                            PageUrl = "/Amministrazione/FattureCloud",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 206,
                            Category = "AMMINISTRAZIONE",
                            Description = "Gestione Bilanci CEE",
                            DisplayOrder = 26,
                            Icon = "fas fa-balance-scale",
                            PageName = "Bilanci CEE",
                            PageUrl = "/Amministrazione/BilanciCEE",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 207,
                            Category = "AMMINISTRAZIONE",
                            Description = "Gestione incassi fatture",
                            DisplayOrder = 27,
                            Icon = "fas fa-money-bill-wave",
                            PageName = "Incassi",
                            PageUrl = "/Amministrazione/Incassi",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 208,
                            Category = "AMMINISTRAZIONE",
                            Description = "Report incassi per professionista",
                            DisplayOrder = 28,
                            Icon = "fas fa-user-tie",
                            PageName = "Report Professionisti",
                            PageUrl = "/Amministrazione/ReportProfessionisti",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 209,
                            Category = "AMMINISTRAZIONE",
                            Description = "Gestione anni di fatturazione",
                            DisplayOrder = 29,
                            Icon = "fas fa-calendar-alt",
                            PageName = "Gestione Anni",
                            PageUrl = "/Amministrazione/GestioneAnni",
                            ShowInMenu = true
                        },
                        new
                        {
                            Id = 210,
                            Description = "Budget Studio - pianificazione spese mensili",
                            DisplayOrder = 30,
                            Icon = "fas fa-coins",
                            PageName = "Budget Studio",
                            PageUrl = "/BudgetStudio",
                            ShowInMenu = true
                        });
                });

            modelBuilder.Entity("StudioCG.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoAccesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cognome = "Sistema",
                            DataCreazione = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@studiocg.it",
                            IsActive = true,
                            IsAdmin = true,
                            Nome = "Amministratore",
                            PasswordHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("StudioCG.Web.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("StudioCG.Web.Models.AttivitaAnnuale", b =>
                {
                    b.HasOne("StudioCG.Web.Models.AnnualitaFiscale", "AnnualitaFiscale")
                        .WithMany("AttivitaAnnuali")
                        .HasForeignKey("AnnualitaFiscaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.AttivitaTipo", "AttivitaTipo")
                        .WithMany("AttivitaAnnuali")
                        .HasForeignKey("AttivitaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnualitaFiscale");

                    b.Navigation("AttivitaTipo");
                });

            modelBuilder.Entity("StudioCG.Web.Models.AttivitaCampo", b =>
                {
                    b.HasOne("StudioCG.Web.Models.AttivitaTipo", "AttivitaTipo")
                        .WithMany("Campi")
                        .HasForeignKey("AttivitaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttivitaTipo");
                });

            modelBuilder.Entity("StudioCG.Web.Models.BudgetStudio.BudgetSpesaMensile", b =>
                {
                    b.HasOne("StudioCG.Web.Models.BudgetStudio.VoceSpesaBudget", "VoceSpesaBudget")
                        .WithMany("BudgetMensile")
                        .HasForeignKey("VoceSpesaBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VoceSpesaBudget");
                });

            modelBuilder.Entity("StudioCG.Web.Models.ClienteAttivita", b =>
                {
                    b.HasOne("StudioCG.Web.Models.AttivitaAnnuale", "AttivitaAnnuale")
                        .WithMany("ClientiAttivita")
                        .HasForeignKey("AttivitaAnnualeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.Cliente", "Cliente")
                        .WithMany("Attivita")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttivitaAnnuale");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("StudioCG.Web.Models.ClienteAttivitaValore", b =>
                {
                    b.HasOne("StudioCG.Web.Models.AttivitaCampo", "AttivitaCampo")
                        .WithMany()
                        .HasForeignKey("AttivitaCampoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.ClienteAttivita", "ClienteAttivita")
                        .WithMany("Valori")
                        .HasForeignKey("ClienteAttivitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttivitaCampo");

                    b.Navigation("ClienteAttivita");
                });

            modelBuilder.Entity("StudioCG.Web.Models.ClienteSoggetto", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Cliente", "Cliente")
                        .WithMany("Soggetti")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicField", b =>
                {
                    b.HasOne("StudioCG.Web.Models.DynamicPage", "DynamicPage")
                        .WithMany("Fields")
                        .HasForeignKey("DynamicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicPage");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicFieldValue", b =>
                {
                    b.HasOne("StudioCG.Web.Models.DynamicField", "DynamicField")
                        .WithMany("FieldValues")
                        .HasForeignKey("DynamicFieldId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.DynamicRecord", "DynamicRecord")
                        .WithMany("FieldValues")
                        .HasForeignKey("DynamicRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicField");

                    b.Navigation("DynamicRecord");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicRecord", b =>
                {
                    b.HasOne("StudioCG.Web.Models.DynamicPage", "DynamicPage")
                        .WithMany("Records")
                        .HasForeignKey("DynamicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicPage");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.AccessoCliente", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.Fatturazione.ScadenzaFatturazione", "ScadenzaFatturazione")
                        .WithMany("AccessiClienti")
                        .HasForeignKey("ScadenzaFatturazioneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.User", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("ScadenzaFatturazione");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.BilancioCEE", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.Fatturazione.ScadenzaFatturazione", "ScadenzaFatturazione")
                        .WithMany("BilanciCEE")
                        .HasForeignKey("ScadenzaFatturazioneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("ScadenzaFatturazione");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.FatturaCloud", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.Fatturazione.ScadenzaFatturazione", "ScadenzaFatturazione")
                        .WithMany("FattureCloud")
                        .HasForeignKey("ScadenzaFatturazioneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("ScadenzaFatturazione");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.IncassoFattura", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Fatturazione.ScadenzaFatturazione", "ScadenzaFatturazione")
                        .WithMany("Incassi")
                        .HasForeignKey("ScadenzaFatturazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScadenzaFatturazione");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.IncassoProfessionista", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Fatturazione.IncassoFattura", "IncassoFattura")
                        .WithMany("SuddivisioneProfessionisti")
                        .HasForeignKey("IncassoFatturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.User", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("IncassoFattura");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.MandatoCliente", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.ScadenzaFatturazione", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.Fatturazione.MandatoCliente", "MandatoCliente")
                        .WithMany("Scadenze")
                        .HasForeignKey("MandatoClienteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("MandatoCliente");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.SpesaPratica", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.Fatturazione.ScadenzaFatturazione", "ScadenzaFatturazione")
                        .WithMany("SpesePratiche")
                        .HasForeignKey("ScadenzaFatturazioneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("StudioCG.Web.Models.User", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cliente");

                    b.Navigation("ScadenzaFatturazione");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("StudioCG.Web.Models.UserPermission", b =>
                {
                    b.HasOne("StudioCG.Web.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudioCG.Web.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudioCG.Web.Models.AnnualitaFiscale", b =>
                {
                    b.Navigation("AttivitaAnnuali");
                });

            modelBuilder.Entity("StudioCG.Web.Models.AttivitaAnnuale", b =>
                {
                    b.Navigation("ClientiAttivita");
                });

            modelBuilder.Entity("StudioCG.Web.Models.AttivitaTipo", b =>
                {
                    b.Navigation("AttivitaAnnuali");

                    b.Navigation("Campi");
                });

            modelBuilder.Entity("StudioCG.Web.Models.BudgetStudio.VoceSpesaBudget", b =>
                {
                    b.Navigation("BudgetMensile");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Cliente", b =>
                {
                    b.Navigation("Attivita");

                    b.Navigation("Soggetti");
                });

            modelBuilder.Entity("StudioCG.Web.Models.ClienteAttivita", b =>
                {
                    b.Navigation("Valori");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicField", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicPage", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("StudioCG.Web.Models.DynamicRecord", b =>
                {
                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.IncassoFattura", b =>
                {
                    b.Navigation("SuddivisioneProfessionisti");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.MandatoCliente", b =>
                {
                    b.Navigation("Scadenze");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Fatturazione.ScadenzaFatturazione", b =>
                {
                    b.Navigation("AccessiClienti");

                    b.Navigation("BilanciCEE");

                    b.Navigation("FattureCloud");

                    b.Navigation("Incassi");

                    b.Navigation("SpesePratiche");
                });

            modelBuilder.Entity("StudioCG.Web.Models.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("StudioCG.Web.Models.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
